-- 1. Create Database safely
IF NOT EXISTS (SELECT * FROM sys.databases WHERE name = 'FoodDeliveryDB')
BEGIN
    CREATE DATABASE FoodDeliveryDB;
END
GO

USE FoodDeliveryDB;
GO

-- 2. Drop Tables if they exist (Reverse order of dependencies)
DROP TABLE IF EXISTS FEEDBACK;
DROP TABLE IF EXISTS DELIVERY;
DROP TABLE IF EXISTS PAYMENT;
DROP TABLE IF EXISTS ORDERITEM;
DROP TABLE IF EXISTS ORDERS;
DROP TABLE IF EXISTS MENUITEM;
DROP TABLE IF EXISTS RESTAURANT_PHONE;
DROP TABLE IF EXISTS RESTAURANT_CUISINETYPE;
DROP TABLE IF EXISTS USER_PHONE;
DROP TABLE IF EXISTS ADDRESS;
DROP TABLE IF EXISTS RESTAURANT;
DROP TABLE IF EXISTS [USER];
GO

-- 3. USER Table
CREATE TABLE [USER] (
    UserID       INT          NOT NULL IDENTITY(1,1),
    FirstName    VARCHAR(100) NOT NULL,
    LastName     VARCHAR(100) NOT NULL,
    Email        VARCHAR(255) NOT NULL,
    PasswordHash VARCHAR(255) NOT NULL,
    UserName     VARCHAR(100) NOT NULL,
    CreatedAt    DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UserType     VARCHAR(20)  NOT NULL DEFAULT 'customer' CHECK (UserType IN ('customer','driver','admin')),

    CONSTRAINT PK_USER          PRIMARY KEY (UserID),
    CONSTRAINT UQ_USER_Email    UNIQUE (Email),
    CONSTRAINT UQ_USER_UserName UNIQUE (UserName)
);

-- 4. USER_PHONE
CREATE TABLE USER_PHONE (
    Phone  VARCHAR(20) NOT NULL,
    UserID INT          NOT NULL,

    CONSTRAINT PK_USER_PHONE  PRIMARY KEY (Phone),
    CONSTRAINT FK_UPHONE_USER FOREIGN KEY (UserID) REFERENCES [USER] (UserID) ON DELETE CASCADE ON UPDATE CASCADE
);

-- 5. ADDRESS
CREATE TABLE ADDRESS (
    AddressID    INT          NOT NULL IDENTITY(1,1),
    City         VARCHAR(100) NOT NULL,
    StreetName   VARCHAR(150) NOT NULL,
    StreetNumber VARCHAR(20)  NOT NULL,
    Apartment    VARCHAR(50)  NULL,
    PostalCode   VARCHAR(20)  NULL,
    IsDefault    BIT          NULL DEFAULT 0,
    UserID       INT          NULL,

    CONSTRAINT PK_ADDRESS   PRIMARY KEY (AddressID),
    CONSTRAINT FK_ADDR_USER FOREIGN KEY (UserID) REFERENCES [USER] (UserID) ON DELETE SET NULL ON UPDATE CASCADE
);

-- 6. RESTAURANT
CREATE TABLE RESTAURANT (
    RestaurantID INT            NOT NULL IDENTITY(1,1),
    Name         VARCHAR(150)   NOT NULL,
    Rating       DECIMAL(3,2)   NULL CHECK (Rating BETWEEN 0 AND 5),
    IsActive     BIT            NOT NULL DEFAULT 1,
    City         VARCHAR(100)   NOT NULL,
    StreetName   VARCHAR(150)   NOT NULL,
    StreetNumber VARCHAR(20)    NOT NULL,
    Unit         VARCHAR(50)    NULL,

    CONSTRAINT PK_RESTAURANT PRIMARY KEY (RestaurantID)
);

-- 7. RESTAURANT_CUISINETYPE
CREATE TABLE RESTAURANT_CUISINETYPE (
    RestaurantID INT          NOT NULL,
    CuisineType  VARCHAR(100) NOT NULL,

    CONSTRAINT PK_RCT      PRIMARY KEY (RestaurantID, CuisineType),
    CONSTRAINT FK_RCT_REST FOREIGN KEY (RestaurantID) REFERENCES RESTAURANT (RestaurantID) ON DELETE CASCADE ON UPDATE CASCADE
);

-- 8. RESTAURANT_PHONE
CREATE TABLE RESTAURANT_PHONE (
    Phone        VARCHAR(20) NOT NULL,
    RestaurantID INT          NOT NULL,

    CONSTRAINT PK_RPHONE      PRIMARY KEY (Phone),
    CONSTRAINT FK_RPHONE_REST FOREIGN KEY (RestaurantID) REFERENCES RESTAURANT (RestaurantID) ON DELETE CASCADE ON UPDATE CASCADE
);

-- 9. MENUITEM
CREATE TABLE MENUITEM (
    ItemID       INT           NOT NULL IDENTITY(1,1),
    RestaurantID INT           NOT NULL,
    Name         VARCHAR(150)  NOT NULL,
    Price        DECIMAL(10,2) NOT NULL CHECK (Price >= 0),
    Description  VARCHAR(MAX)  NULL,
    IsAvailable  BIT           NOT NULL DEFAULT 1,

    CONSTRAINT PK_MENUITEM  PRIMARY KEY (ItemID),
    CONSTRAINT FK_MENU_REST FOREIGN KEY (RestaurantID) REFERENCES RESTAURANT (RestaurantID) ON DELETE CASCADE ON UPDATE CASCADE
);

-- 10. ORDERS
CREATE TABLE ORDERS (
    OrderID    INT           NOT NULL IDENTITY(1,1),
    UserID     INT           NOT NULL,
    Status     VARCHAR(20)   NOT NULL DEFAULT 'pending' CHECK (Status IN ('pending','confirmed','preparing','out_for_delivery','delivered','cancelled')),
    TotalPrice DECIMAL(10,2) NOT NULL CHECK (TotalPrice >= 0),
    OrderDate  DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT PK_ORDERS      PRIMARY KEY (OrderID),
    CONSTRAINT FK_ORDERS_USER FOREIGN KEY (UserID) REFERENCES [USER] (UserID) ON DELETE NO ACTION ON UPDATE CASCADE
);

-- 11. ORDERITEM
CREATE TABLE ORDERITEM (
    OrderItemID INT           NOT NULL IDENTITY(1,1),
    OrderID     INT           NOT NULL,
    ItemID      INT           NOT NULL,
    Quantity    INT           NOT NULL CHECK (Quantity > 0),
    UnitPrice   DECIMAL(10,2) NOT NULL CHECK (UnitPrice >= 0),

    CONSTRAINT PK_ORDERITEM PRIMARY KEY (OrderItemID),
    CONSTRAINT FK_OI_ORDER  FOREIGN KEY (OrderID) REFERENCES ORDERS (OrderID) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FK_OI_MENU   FOREIGN KEY (ItemID) REFERENCES MENUITEM (ItemID) ON DELETE NO ACTION ON UPDATE CASCADE
);

-- 12. PAYMENT
CREATE TABLE PAYMENT (
    PaymentID     INT           NOT NULL IDENTITY(1,1),
    OrderID       INT           NOT NULL,
    Amount        DECIMAL(10,2) NOT NULL CHECK (Amount >= 0),
    Method        VARCHAR(20)   NOT NULL CHECK (Method IN ('cash','credit_card','debit_card','online_wallet','bank_transfer')),
    PaymentTime   DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PaymentStatus VARCHAR(20)   NOT NULL DEFAULT 'pending' CHECK (PaymentStatus IN ('pending','completed','failed','refunded')),

    CONSTRAINT PK_PAYMENT   PRIMARY KEY (PaymentID),
    CONSTRAINT FK_PAY_ORDER FOREIGN KEY (OrderID) REFERENCES ORDERS (OrderID) ON DELETE NO ACTION ON UPDATE CASCADE,
    CONSTRAINT UQ_PAY_ORDER UNIQUE (OrderID)
);

-- 13. DELIVERY
CREATE TABLE DELIVERY (
    DeliveryID     INT      NOT NULL IDENTITY(1,1),
    OrderID        INT      NOT NULL,
    UserID         INT      NOT NULL,
    AddressID      INT      NOT NULL,
    PickupTime     DATETIME NULL,
    DeliveryTime   DATETIME NULL,
    DeliveryStatus VARCHAR(20) NOT NULL DEFAULT 'assigned' CHECK (DeliveryStatus IN ('assigned','picked_up','in_transit','delivered','failed')),

    CONSTRAINT PK_DELIVERY   PRIMARY KEY (DeliveryID),
    CONSTRAINT FK_DEL_ORDER  FOREIGN KEY (OrderID) REFERENCES ORDERS (OrderID) ON DELETE NO ACTION ON UPDATE CASCADE,
    CONSTRAINT FK_DEL_DRIVER FOREIGN KEY (UserID) REFERENCES [USER] (UserID) ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT FK_DEL_ADDR   FOREIGN KEY (AddressID) REFERENCES ADDRESS (AddressID) ON DELETE NO ACTION ON UPDATE NO ACTION
);

-- 14. FEEDBACK
CREATE TABLE FEEDBACK (
    FeedbackID   INT      NOT NULL IDENTITY(1,1),
    UserID       INT      NOT NULL,
    OrderID      INT      NOT NULL,
    RestaurantID INT      NOT NULL,
    Rating       TINYINT  NOT NULL CHECK (Rating BETWEEN 1 AND 5),
    Comment      VARCHAR(MAX) NULL,
    FeedbackDate DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT PK_FEEDBACK  PRIMARY KEY (FeedbackID),
    CONSTRAINT FK_FB_USER   FOREIGN KEY (UserID) REFERENCES [USER] (UserID) ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT FK_FB_ORDER  FOREIGN KEY (OrderID) REFERENCES ORDERS (OrderID) ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT FK_FB_REST   FOREIGN KEY (RestaurantID) REFERENCES RESTAURANT (RestaurantID) ON DELETE NO ACTION ON UPDATE NO ACTION
);
GO

-- 15. INDEXES
CREATE INDEX IDX_UPHONE_USER ON USER_PHONE  (UserID);
CREATE INDEX IDX_ADDR_USER   ON ADDRESS     (UserID);
CREATE INDEX IDX_MENU_REST   ON MENUITEM    (RestaurantID);
CREATE INDEX IDX_ORDERS_USER ON ORDERS      (UserID);
CREATE INDEX IDX_OI_ORDER    ON ORDERITEM   (OrderID);
CREATE INDEX IDX_OI_ITEM     ON ORDERITEM   (ItemID);
CREATE INDEX IDX_DEL_ORDER   ON DELIVERY    (OrderID);
CREATE INDEX IDX_DEL_DRIVER  ON DELIVERY    (UserID);
CREATE INDEX IDX_DEL_ADDR    ON DELIVERY    (AddressID);
CREATE INDEX IDX_FB_USER     ON FEEDBACK    (UserID);
CREATE INDEX IDX_FB_ORDER    ON FEEDBACK    (OrderID);
CREATE INDEX IDX_FB_REST     ON FEEDBACK    (RestaurantID);
GO

-- Verification for SQL Server
SELECT TABLE_NAME 
FROM INFORMATION_SCHEMA.TABLES 
WHERE TABLE_TYPE = 'BASE TABLE'
ORDER BY TABLE_NAME;